# Generated by Django 5.2.4 on 2025-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('categorie', models.CharField(choices=[('portrait', 'Portrait'), ('paysage', 'Paysage'), ('abstrait', 'Abstrait'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
