# Generated by Django 5.2.4 on 2025-08-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('format', models.CharField(choices=[('A4', 'A4 (21x29.7 cm)'), ('A3', 'A3 (29.7x42 cm)'), ('A2', 'A2 (42x59.4 cm)')], default='A4', max_length=10)),
                ('style', models.CharField(choices=[('portrait', 'Portrait'), ('dessin', 'Dessin'), ('croquis', 'Croquis')], default='Portrait', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_reference', models.ImageField(blank=True, null=True, upload_to='references/')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='oeuvres/')),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.categorie')),
            ],
        ),
    ]
