# Generated by Django 5.2.4 on 2025-07-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
    ]
