# Generated by Django 5.2.4 on 2025-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
