# Generated by Django 5.2.4 on 2025-08-04 17:53

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_commande_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='oeuvres/'),
        ),
    ]
