# Generated by Django 5.2.4 on 2025-07-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_categorie_nom_alter_oeuvre_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='telephone',
        ),
        migrations.AddField(
            model_name='commande',
            name='format',
            field=models.CharField(choices=[('A4', 'A4 (21x29.7 cm)'), ('A3', 'A3 (29.7x42 cm)'), ('A2', 'A2 (42x59.4 cm)')], default='A4', max_length=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='image_reference',
            field=models.ImageField(blank=True, null=True, upload_to='references/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='style',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('dessin', 'Dessin'), ('croquis', 'Croquis')], default='Portrait', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.categorie'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
