# Generated by Django 5.2.4 on 2025-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='image',
            field=models.ImageField(upload_to='oeuvres/'),
        ),
    ]
