# Generated by Django 5.2.4 on 2025-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_oeuvre_categorie_alter_oeuvre_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='categorie',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('paysage', 'Paysage'), ('abstrait', 'Abstrait'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
