# Generated by Django 5.2.4 on 2025-08-06 09:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_oeuvre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='image_reference',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
