# Generated by Django 5.2.4 on 2025-08-07 11:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_commande_image_reference_alter_oeuvre_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_slide_1', models.CharField(default='Offrez-vous un portrait d’exception', max_length=200)),
                ('texte_slide_1', models.TextField(default='Des œuvres uniques réalisées à la main.')),
                ('titre_slide_2', models.CharField(default='Des portraits faits avec passion', max_length=200)),
                ('texte_slide_2', models.TextField(default='Capturer l’essence de chaque regard.')),
                ('image_accueil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Image d'accueil")),
                ('image_profil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de profil')),
            ],
        ),
    ]
