# Generated by Django 5.2.4 on 2025-08-12 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='avis',
            new_name='texte',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='visible',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
